version: "3.8"

services:
  personalphotodb:
    image: mcr.microsoft.com/mssql/server:2019-latest  
    container_name: personalphotodb
    environment:
        SA_PASSWORD: "Asd123)_"
        ACCEPT_EULA: Y
    restart: always
    volumes:
    - sqlserver_data:/var/opt/mssql
    ports:
    - "1433:1433"
volumes:
  sqlserver_data:
    name: sqlserver_data